version: "3.9"

services:
    #my app
    app:
        container_name: app
        build:
            context: .
            cache_from:
                - golang:alpine
        restart: always
        depends_on:
            migrate:
                condition: service_completed_successfully

    #Redis Database
    redisdb:
        container_name: RedisDB
        image: redis:alpine
        restart: always

    #MySQL Database
    mysqldb:
        container_name: MySQLdb
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DBNAME
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 5s
            timeout: 5s
            retries: 20

    #PHPMyAdmin for MySQL
    phpmyadmin:
        container_name: PHPMyAdmin
        image: phpmyadmin
        ports:
            - 80:80
        environment:
            PMA_HOST: mysqldb

    #Migrate DB
    migrate:
        container_name: db_migration
        image: migrate/migrate
        volumes:
            - ./internal/repo/migration:/migration
        command:
            [
                "-path",
                "/migration",
                "-database",
                "mysql://$MYSQL_USER:$MYSQL_PASSWORD@tcp(mysqldb:3306)/$MYSQL_DBNAME",
                "up",
            ]
        depends_on:
            mysqldb:
                condition: service_healthy
