// Code generated by MockGen. DO NOT EDIT.
// Source: gold-panel/internal/service/v1 (interfaces: IService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "gold-panel/internal/service/v1"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// WorkerAdd mocks base method.
func (m *MockIService) WorkerAdd(arg0 context.Context, arg1 *service.WorkerAddDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerAdd", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkerAdd indicates an expected call of WorkerAdd.
func (mr *MockIServiceMockRecorder) WorkerAdd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerAdd", reflect.TypeOf((*MockIService)(nil).WorkerAdd), arg0, arg1)
}

// WorkerGetAllID mocks base method.
func (m *MockIService) WorkerGetAllID(arg0 context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerGetAllID", arg0)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerGetAllID indicates an expected call of WorkerGetAllID.
func (mr *MockIServiceMockRecorder) WorkerGetAllID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerGetAllID", reflect.TypeOf((*MockIService)(nil).WorkerGetAllID), arg0)
}

// WorkerGetToken mocks base method.
func (m *MockIService) WorkerGetToken(arg0 context.Context, arg1 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerGetToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkerGetToken indicates an expected call of WorkerGetToken.
func (mr *MockIServiceMockRecorder) WorkerGetToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerGetToken", reflect.TypeOf((*MockIService)(nil).WorkerGetToken), arg0, arg1)
}
